import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../core/player_profile.dart';
import '../core/fact_tracker.dart';
import '../core/achievement.dart';
import '../core/daily_challenge.dart';
import 'migration.dart';

class LocalStorage {
  static const String _profileBoxName = 'player_profile';
  static const String _factsBoxName = 'fact_history';
  static const String _metaBoxName = 'app_meta';
  static const String _achievementsBoxName = 'achievements';
  static const String _dailyChallengeBoxName = 'daily_challenges';
  static const String _profileKey = 'current_profile';
  static const String _schemaVersionKey = 'schema_version';

  late Box<PlayerProfile> _profileBox;
  late Box<FactRecord> _factsBox;
  late Box<dynamic> _metaBox;
  late Box<UnlockedAchievement> _achievementsBox;
  late Box<DailyChallengeState> _dailyChallengeBox;

  bool _initialized = false;
  bool _closed = false;

  /// Callback fired after any data write. Used by CloudSync to schedule sync.
  void Function()? onDataChanged;

  /// Reactive notifier for the current player profile.
  /// Listen via ValueListenableBuilder to rebuild UI on profile changes.
  final ValueNotifier<PlayerProfile> profileNotifier =
      ValueNotifier(PlayerProfile(id: 'default'));

  /// Initialize Hive and open all boxes. Call once at app startup before runApp.
  Future<void> initialize() async {
    if (_initialized) return;

    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    Hive.registerAdapter(PlayerProfileAdapter());
    Hive.registerAdapter(GameStatsAdapter());
    Hive.registerAdapter(PlayerSettingsAdapter());
    Hive.registerAdapter(FactRecordAdapter());
    Hive.registerAdapter(FactStatusAdapter());
    Hive.registerAdapter(UnlockedAchievementAdapter());
    Hive.registerAdapter(DailyChallengeStateAdapter());

    // Open boxes — if corrupted, delete and recreate
    try {
      _profileBox = await Hive.openBox<PlayerProfile>(_profileBoxName);
      _factsBox = await Hive.openBox<FactRecord>(_factsBoxName);
      _metaBox = await Hive.openBox(_metaBoxName);
      _achievementsBox =
          await Hive.openBox<UnlockedAchievement>(_achievementsBoxName);
      _dailyChallengeBox =
          await Hive.openBox<DailyChallengeState>(_dailyChallengeBoxName);
    } catch (e) {
      debugPrint('LocalStorage: Hive boxes corrupted, resetting: $e');
      await Hive.deleteFromDisk();
      await Hive.initFlutter();
      _profileBox = await Hive.openBox<PlayerProfile>(_profileBoxName);
      _factsBox = await Hive.openBox<FactRecord>(_factsBoxName);
      _metaBox = await Hive.openBox(_metaBoxName);
      _achievementsBox =
          await Hive.openBox<UnlockedAchievement>(_achievementsBoxName);
      _dailyChallengeBox =
          await Hive.openBox<DailyChallengeState>(_dailyChallengeBoxName);
    }

    // Run migrations
    await MigrationRunner.run(this);

    profileNotifier.value = getProfile();

    _initialized = true;
  }

  // ---- Profile ----

  /// Get the current player profile, or create a default one if none exists.
  PlayerProfile getProfile() {
    return _profileBox.get(_profileKey) ?? _createDefaultProfile();
  }

  /// Save the player profile.
  Future<void> saveProfile(PlayerProfile profile) async {
    if (_closed) return;
    await _profileBox.put(_profileKey, profile);
    profileNotifier.value = profile;
    onDataChanged?.call();
  }

  /// Update the profile using a transform function.
  /// Returns the updated profile.
  Future<PlayerProfile> updateProfile(
    PlayerProfile Function(PlayerProfile current) transform,
  ) async {
    final current = getProfile();
    final updated = transform(current);
    await saveProfile(updated);
    return updated;
  }

  PlayerProfile _createDefaultProfile() {
    final profile = PlayerProfile(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
    );
    _profileBox.put(_profileKey, profile);
    return profile;
  }

  // ---- Fact History ----

  /// Get a fact record by its key (e.g., "7x8", "15-9").
  FactRecord? getFact(String factKey) {
    return _factsBox.get(factKey);
  }

  /// Save or update a fact record.
  Future<void> saveFact(FactRecord fact) async {
    if (_closed) return;
    await _factsBox.put(fact.factKey, fact);
    onDataChanged?.call();
  }

  /// Get all recorded facts.
  List<FactRecord> getAllFacts() {
    return _factsBox.values.toList();
  }

  /// Get facts filtered by status.
  List<FactRecord> getFactsByStatus(FactStatus status) {
    return _factsBox.values.where((f) => f.status == status).toList();
  }

  /// Count facts by status.
  Map<FactStatus, int> getFactStatusCounts() {
    final counts = <FactStatus, int>{};
    for (final status in FactStatus.values) {
      counts[status] = 0;
    }
    for (final fact in _factsBox.values) {
      counts[fact.status] = (counts[fact.status] ?? 0) + 1;
    }
    return counts;
  }

  // ---- Achievements ----

  /// Save an unlocked achievement.
  Future<void> saveUnlockedAchievement(UnlockedAchievement achievement) async {
    if (_closed) return;
    await _achievementsBox.put(achievement.achievementId, achievement);
    onDataChanged?.call();
  }

  /// Get the set of unlocked achievement IDs.
  Set<String> getUnlockedAchievementIds() {
    return _achievementsBox.keys.cast<String>().toSet();
  }

  /// Get all unlocked achievements.
  List<UnlockedAchievement> getAllUnlockedAchievements() {
    return _achievementsBox.values.toList();
  }

  // ---- Daily Challenges ----

  /// Save daily challenge completion state for a specific date.
  Future<void> saveDailyChallengeState(DailyChallengeState state) async {
    if (_closed) return;
    await _dailyChallengeBox.put(state.dateKey, state);
    onDataChanged?.call();
  }

  /// Get daily challenge state for a specific date key (e.g., "2026-02-16").
  DailyChallengeState? getDailyChallengeState(String dateKey) {
    return _dailyChallengeBox.get(dateKey);
  }

  /// Count total daily challenges completed (all-time).
  int getTotalDailyChallengesCompleted() {
    return _dailyChallengeBox.values
        .where((s) => s.allComplete)
        .length;
  }

  // ---- Meta ----

  int get schemaVersion =>
      _metaBox.get(_schemaVersionKey, defaultValue: 0) as int;

  Future<void> setSchemaVersion(int version) async {
    if (_closed) return;
    await _metaBox.put(_schemaVersionKey, version);
  }

  /// Get an arbitrary metadata value by key.
  dynamic getMeta(String key) => _metaBox.get(key);

  /// Set an arbitrary metadata value by key.
  Future<void> setMeta(String key, dynamic value) async {
    if (_closed) return;
    await _metaBox.put(key, value);
  }

  // ---- Lifecycle ----

  Future<void> close() async {
    _closed = true;
    profileNotifier.dispose();
    await _profileBox.close();
    await _factsBox.close();
    await _metaBox.close();
    await _achievementsBox.close();
    await _dailyChallengeBox.close();
  }

  /// Delete all data. Used only for development/testing.
  Future<void> clearAll() async {
    await _profileBox.clear();
    await _factsBox.clear();
    await _metaBox.clear();
    await _achievementsBox.clear();
    await _dailyChallengeBox.clear();
  }
}
